# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.25.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.25.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/protikpaul/Desktop/TP_Aided_MPC/dirigentv2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/protikpaul/Desktop/TP_Aided_MPC/dirigentv2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.25.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.25.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.25.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/protikpaul/Desktop/TP_Aided_MPC/dirigentv2/CMakeFiles /Users/protikpaul/Desktop/TP_Aided_MPC/dirigentv2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/protikpaul/Desktop/TP_Aided_MPC/dirigentv2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named QuadSquad

# Build rule for target.
QuadSquad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QuadSquad
.PHONY : QuadSquad

# fast build rule for target.
QuadSquad/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/QuadSquad.dir/build.make src/CMakeFiles/QuadSquad.dir/build
.PHONY : QuadSquad/fast

#=============================================================================
# Target rules for targets named Dirigent

# Build rule for target.
Dirigent: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Dirigent
.PHONY : Dirigent

# fast build rule for target.
Dirigent/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Dirigent.dir/build.make src/CMakeFiles/Dirigent.dir/build
.PHONY : Dirigent/fast

#=============================================================================
# Target rules for targets named online_mpc

# Build rule for target.
online_mpc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 online_mpc
.PHONY : online_mpc

# fast build rule for target.
online_mpc/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/online_mpc.dir/build.make benchmark/CMakeFiles/online_mpc.dir/build
.PHONY : online_mpc/fast

#=============================================================================
# Target rules for targets named online_nn

# Build rule for target.
online_nn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 online_nn
.PHONY : online_nn

# fast build rule for target.
online_nn/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/online_nn.dir/build.make benchmark/CMakeFiles/online_nn.dir/build
.PHONY : online_nn/fast

#=============================================================================
# Target rules for targets named offline_mpc_tp

# Build rule for target.
offline_mpc_tp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 offline_mpc_tp
.PHONY : offline_mpc_tp

# fast build rule for target.
offline_mpc_tp/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/offline_mpc_tp.dir/build.make benchmark/CMakeFiles/offline_mpc_tp.dir/build
.PHONY : offline_mpc_tp/fast

#=============================================================================
# Target rules for targets named offline_mpc_sub

# Build rule for target.
offline_mpc_sub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 offline_mpc_sub
.PHONY : offline_mpc_sub

# fast build rule for target.
offline_mpc_sub/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/offline_mpc_sub.dir/build.make benchmark/CMakeFiles/offline_mpc_sub.dir/build
.PHONY : offline_mpc_sub/fast

#=============================================================================
# Target rules for targets named sodo_gridlock_iter

# Build rule for target.
sodo_gridlock_iter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sodo_gridlock_iter
.PHONY : sodo_gridlock_iter

# fast build rule for target.
sodo_gridlock_iter/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/sodo_gridlock_iter.dir/build.make benchmark/CMakeFiles/sodo_gridlock_iter.dir/build
.PHONY : sodo_gridlock_iter/fast

#=============================================================================
# Target rules for targets named benchmarks

# Build rule for target.
benchmarks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmarks
.PHONY : benchmarks

# fast build rule for target.
benchmarks/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/benchmarks.dir/build.make benchmark/CMakeFiles/benchmarks.dir/build
.PHONY : benchmarks/fast

#=============================================================================
# Target rules for targets named io_test

# Build rule for target.
io_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 io_test
.PHONY : io_test

# fast build rule for target.
io_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/io_test.dir/build.make test/CMakeFiles/io_test.dir/build
.PHONY : io_test/fast

#=============================================================================
# Target rules for targets named sharing_test

# Build rule for target.
sharing_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sharing_test
.PHONY : sharing_test

# fast build rule for target.
sharing_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/sharing_test.dir/build.make test/CMakeFiles/sharing_test.dir/build
.PHONY : sharing_test/fast

#=============================================================================
# Target rules for targets named utils_test

# Build rule for target.
utils_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 utils_test
.PHONY : utils_test

# fast build rule for target.
utils_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/utils_test.dir/build.make test/CMakeFiles/utils_test.dir/build
.PHONY : utils_test/fast

#=============================================================================
# Target rules for targets named rand_test

# Build rule for target.
rand_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rand_test
.PHONY : rand_test

# fast build rule for target.
rand_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/rand_test.dir/build.make test/CMakeFiles/rand_test.dir/build
.PHONY : rand_test/fast

#=============================================================================
# Target rules for targets named offline_test

# Build rule for target.
offline_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 offline_test
.PHONY : offline_test

# fast build rule for target.
offline_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/offline_test.dir/build.make test/CMakeFiles/offline_test.dir/build
.PHONY : offline_test/fast

#=============================================================================
# Target rules for targets named online_test

# Build rule for target.
online_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 online_test
.PHONY : online_test

# fast build rule for target.
online_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/online_test.dir/build.make test/CMakeFiles/online_test.dir/build
.PHONY : online_test/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/tests.dir/build.make test/CMakeFiles/tests.dir/build
.PHONY : tests/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... benchmarks"
	@echo "... tests"
	@echo "... Dirigent"
	@echo "... QuadSquad"
	@echo "... io_test"
	@echo "... offline_mpc_sub"
	@echo "... offline_mpc_tp"
	@echo "... offline_test"
	@echo "... online_mpc"
	@echo "... online_nn"
	@echo "... online_test"
	@echo "... rand_test"
	@echo "... sharing_test"
	@echo "... sodo_gridlock_iter"
	@echo "... utils_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

